### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by ap0181** [iyotetsuya/RectangleDetection#11]
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.github.iyotetsuya.rectangledetection.views.CameraPreview
                                                                                          Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class io.github.iyotetsuya.rectangledetection.views.CameraPreview

 Process: io.github.iyotetsuya.rectangledetection, PID: 16380
                                                                                         java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.iyotetsuya.rectangledetection/io.github.iyotetsuya.rectangledetection.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class io.github.iyotetsuya.rectangledetection.views.CameraPreview
                                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2706)
                                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
                                                                                             at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:163)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6221)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by ap0181** [comment]
Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                                             at android.hardware.Camera.<init>(Camera.java:579)
                                                                                             at android.hardware.Camera.open(Camera.java:419)
                                                                                             at io.github.iyotetsuya.rectangledetection.views.CameraPreview.<init>(CameraPreview.java:71)

**Comment by iyotetsuya** [comment]
fyi, ref: https://developer.android.com/reference/android/hardware/Camera#open(int)

RuntimeException | if opening the camera fails (for example, if the camera is in use by another process or device policy manager has disabled the camera).
-- | --

**Comment by iyotetsuya** [comment]
issue closed. if you have another problem please reopen it.
